export interface Food {
  id: string;
  name: string;
  description: string;
  imageUrl: string;
  category: string;
  calories: string;
}

export const FOODS: Food[] = [
  // Happy foods
  {
    id: 'ice-cream',
    name: 'Artisan Ice Cream',
    description: 'Creamy, handcrafted gelato with fresh berries and a waffle cone',
    imageUrl: 'https://images.unsplash.com/photo-1501443762994-82bd5dace89a?w=400&h=300&fit=crop',
    category: 'Dessert',
    calories: '320 kcal',
  },
  {
    id: 'pizza',
    name: 'Neapolitan Pizza',
    description: 'Wood-fired pizza with San Marzano tomatoes and fresh mozzarella',
    imageUrl: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=400&h=300&fit=crop',
    category: 'Italian',
    calories: '450 kcal',
  },
  {
    id: 'smoothie-bowl',
    name: 'Acai Smoothie Bowl',
    description: 'Vibrant acai blend topped with granola, fresh fruits, and honey',
    imageUrl: 'https://images.unsplash.com/photo-1590301157890-4810ed352733?w=400&h=300&fit=crop',
    category: 'Healthy',
    calories: '280 kcal',
  },
  // Sad foods (comfort food)
  {
    id: 'chocolate-cake',
    name: 'Dark Chocolate Cake',
    description: 'Rich, decadent chocolate cake with velvety ganache frosting',
    imageUrl: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=400&h=300&fit=crop',
    category: 'Dessert',
    calories: '520 kcal',
  },
  {
    id: 'mac-cheese',
    name: 'Truffle Mac & Cheese',
    description: 'Creamy baked mac and cheese with black truffle and breadcrumb topping',
    imageUrl: 'https://images.unsplash.com/photo-1543339494-b4cd4f7ba686?w=400&h=300&fit=crop',
    category: 'Comfort',
    calories: '580 kcal',
  },
  {
    id: 'ramen',
    name: 'Tonkotsu Ramen',
    description: 'Rich pork bone broth with chashu, soft-boiled egg, and nori',
    imageUrl: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=400&h=300&fit=crop',
    category: 'Japanese',
    calories: '490 kcal',
  },
  // Angry foods (spicy/crunchy)
  {
    id: 'hot-wings',
    name: 'Nashville Hot Wings',
    description: 'Fiery cayenne-spiced crispy chicken wings with ranch dip',
    imageUrl: 'https://images.unsplash.com/photo-1567620832903-9fc6debc209f?w=400&h=300&fit=crop',
    category: 'Spicy',
    calories: '420 kcal',
  },
  {
    id: 'tacos',
    name: 'Street Tacos Al Pastor',
    description: 'Marinated pork tacos with pineapple, cilantro, and spicy salsa',
    imageUrl: 'https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?w=400&h=300&fit=crop',
    category: 'Mexican',
    calories: '380 kcal',
  },
  {
    id: 'pad-thai',
    name: 'Fiery Pad Thai',
    description: 'Wok-tossed rice noodles with shrimp, peanuts, and chili flakes',
    imageUrl: 'https://images.unsplash.com/photo-1559314809-0d155014e29e?w=400&h=300&fit=crop',
    category: 'Thai',
    calories: '410 kcal',
  },
  // Anxious foods (calming)
  {
    id: 'green-tea',
    name: 'Matcha Latte',
    description: 'Ceremonial grade matcha whisked with oat milk and light honey',
    imageUrl: 'https://images.unsplash.com/photo-1536256263959-770b48d82b0a?w=400&h=300&fit=crop',
    category: 'Beverage',
    calories: '120 kcal',
  },
  {
    id: 'soup',
    name: 'Miso Soup',
    description: 'Warm dashi broth with silken tofu, wakame, and green onion',
    imageUrl: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=400&h=300&fit=crop',
    category: 'Japanese',
    calories: '75 kcal',
  },
  {
    id: 'oatmeal',
    name: 'Golden Oatmeal',
    description: 'Warm oats with turmeric, banana, walnuts, and maple syrup',
    imageUrl: 'https://images.unsplash.com/photo-1517673400267-0251440c45dc?w=400&h=300&fit=crop',
    category: 'Breakfast',
    calories: '310 kcal',
  },
  // Tired foods (energy boosting)
  {
    id: 'coffee',
    name: 'Espresso Affogato',
    description: 'Double shot espresso poured over creamy vanilla gelato',
    imageUrl: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=400&h=300&fit=crop',
    category: 'Beverage',
    calories: '180 kcal',
  },
  {
    id: 'avocado-toast',
    name: 'Avocado Toast',
    description: 'Sourdough toast with smashed avocado, poached egg, and chili flakes',
    imageUrl: 'https://images.unsplash.com/photo-1541519227354-08fa5d50c44d?w=400&h=300&fit=crop',
    category: 'Breakfast',
    calories: '350 kcal',
  },
  {
    id: 'energy-bowl',
    name: 'Power Protein Bowl',
    description: 'Quinoa bowl with grilled chicken, avocado, edamame, and tahini',
    imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400&h=300&fit=crop',
    category: 'Healthy',
    calories: '480 kcal',
  },
  // Excited foods (celebration)
  {
    id: 'sushi',
    name: 'Rainbow Sushi Platter',
    description: 'Premium assorted nigiri and maki rolls with wasabi and pickled ginger',
    imageUrl: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=400&h=300&fit=crop',
    category: 'Japanese',
    calories: '420 kcal',
  },
  {
    id: 'steak',
    name: 'Wagyu Steak',
    description: 'A5 Wagyu ribeye seared to perfection with truffle butter',
    imageUrl: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=400&h=300&fit=crop',
    category: 'Premium',
    calories: '650 kcal',
  },
  {
    id: 'champagne-cake',
    name: 'Champagne Cupcakes',
    description: 'Delicate champagne-infused cupcakes with buttercream and gold leaf',
    imageUrl: 'https://images.unsplash.com/photo-1486427944544-d2c246c4df14?w=400&h=300&fit=crop',
    category: 'Dessert',
    calories: '290 kcal',
  },
  // Calm foods
  {
    id: 'salad',
    name: 'Mediterranean Salad',
    description: 'Fresh greens with feta, olives, cucumber, and lemon vinaigrette',
    imageUrl: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=400&h=300&fit=crop',
    category: 'Healthy',
    calories: '220 kcal',
  },
  {
    id: 'herbal-tea',
    name: 'Chamomile Tea',
    description: 'Soothing chamomile blend with lavender and a touch of honey',
    imageUrl: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=400&h=300&fit=crop',
    category: 'Beverage',
    calories: '15 kcal',
  },
  {
    id: 'poke-bowl',
    name: 'Salmon Poke Bowl',
    description: 'Fresh salmon cubes with sushi rice, mango, avocado, and ponzu',
    imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400&h=300&fit=crop',
    category: 'Healthy',
    calories: '390 kcal',
  },
  // Sick foods
  {
    id: 'chicken-soup',
    name: 'Chicken Noodle Soup',
    description: 'Classic healing broth with tender chicken, vegetables, and egg noodles',
    imageUrl: 'https://images.unsplash.com/photo-1604152135912-04a022e23696?w=400&h=300&fit=crop',
    category: 'Comfort',
    calories: '190 kcal',
  },
  {
    id: 'ginger-tea',
    name: 'Ginger Lemon Tea',
    description: 'Fresh ginger root steeped with lemon and raw honey',
    imageUrl: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400&h=300&fit=crop',
    category: 'Beverage',
    calories: '45 kcal',
  },
  {
    id: 'congee',
    name: 'Silky Rice Congee',
    description: 'Slow-cooked rice porridge with poached chicken and crispy shallots',
    imageUrl: 'https://images.unsplash.com/photo-1555126634-323283e090fa?w=400&h=300&fit=crop',
    category: 'Asian',
    calories: '215 kcal',
  },
  // Energetic foods
  {
    id: 'smoothie',
    name: 'Green Power Smoothie',
    description: 'Spinach, banana, protein powder, almond butter, and coconut water',
    imageUrl: 'https://images.unsplash.com/photo-1505252585461-04db1eb84625?w=400&h=300&fit=crop',
    category: 'Healthy',
    calories: '260 kcal',
  },
  {
    id: 'peanut-butter-toast',
    name: 'PB & Banana Toast',
    description: 'Whole grain toast with almond butter, sliced banana, and chia seeds',
    imageUrl: 'https://images.unsplash.com/photo-1484723091739-30a097e8f929?w=400&h=300&fit=crop',
    category: 'Breakfast',
    calories: '330 kcal',
  },
  {
    id: 'acai-bowl',
    name: 'Dragon Fruit Bowl',
    description: 'Vibrant pitaya blend with coconut flakes, kiwi, and bee pollen',
    imageUrl: 'https://images.unsplash.com/photo-1494597564530-871f2b93ac55?w=400&h=300&fit=crop',
    category: 'Healthy',
    calories: '290 kcal',
  },
  // Romantic foods
  {
    id: 'chocolate-fondue',
    name: 'Chocolate Fondue',
    description: 'Silky Belgian chocolate with fresh strawberries and marshmallows',
    imageUrl: 'https://images.unsplash.com/photo-1481391319762-47dff72954d9?w=400&h=300&fit=crop',
    category: 'Dessert',
    calories: '410 kcal',
  },
  {
    id: 'pasta',
    name: 'Truffle Pasta',
    description: 'Fresh tagliatelle with black truffle cream sauce and parmesan',
    imageUrl: 'https://images.unsplash.com/photo-1473093295043-cdd812d0e601?w=400&h=300&fit=crop',
    category: 'Italian',
    calories: '520 kcal',
  },
  {
    id: 'wine-cheese',
    name: 'Wine & Cheese Board',
    description: 'Curated selection of artisan cheeses with fruits and crackers',
    imageUrl: 'https://images.unsplash.com/photo-1452195100486-9cc805987862?w=400&h=300&fit=crop',
    category: 'Premium',
    calories: '380 kcal',
  },
  // Thoughtful foods
  {
    id: 'dark-chocolate',
    name: 'Single Origin Chocolate',
    description: '85% cacao dark chocolate bar with sea salt and almonds',
    imageUrl: 'https://images.unsplash.com/photo-1549007994-cb92caebd54b?w=400&h=300&fit=crop',
    category: 'Snack',
    calories: '210 kcal',
  },
  {
    id: 'grain-bowl',
    name: 'Buddha Bowl',
    description: 'Farro base with roasted vegetables, hummus, and tahini drizzle',
    imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400&h=300&fit=crop',
    category: 'Healthy',
    calories: '440 kcal',
  },
  {
    id: 'latte',
    name: 'Vanilla Oat Latte',
    description: 'Perfectly pulled espresso with steamed oat milk and vanilla',
    imageUrl: 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=400&h=300&fit=crop',
    category: 'Beverage',
    calories: '150 kcal',
  },
  // Stressed foods
  {
    id: 'nachos',
    name: 'Loaded Nachos Supreme',
    description: 'Crispy tortilla chips with melted cheese, jalapeños, and guacamole',
    imageUrl: 'https://images.unsplash.com/photo-1513456852971-30c0b8199d4d?w=400&h=300&fit=crop',
    category: 'Comfort',
    calories: '560 kcal',
  },
  {
    id: 'burger',
    name: 'Smash Burger',
    description: 'Double-smashed patties with American cheese, pickles, and special sauce',
    imageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400&h=300&fit=crop',
    category: 'Comfort',
    calories: '650 kcal',
  },
  {
    id: 'fries',
    name: 'Truffle Parmesan Fries',
    description: 'Crispy golden fries tossed with truffle oil, parmesan, and herbs',
    imageUrl: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=400&h=300&fit=crop',
    category: 'Comfort',
    calories: '430 kcal',
  },
];
